<?php

/**
 * Generate
 *
 * @category   Library
 * @package    Generate
 * @subpackage Generator
 */
/**
 * @see Generator_Abstract
 */
require_once 'generator_abstract_predefined.php';

/**
 * Class for generating city.
 *
 * @category   Library
 * @package    Generator
 * @subpackage City
 */
class Generator_City extends Generator_Abstract_Predefined
{
    /**
     * Predefined cities
     *
     * @var array
     */
    protected $_predefinedValues = array(
        'Aberdeen',
        'Abilene',
        'Ada',
        'Agat',
        'Agawam',
        'Agoura Hills',
        'Aguadilla',
        'Akron',
        'Alameda',
        'Alamogordo',
        'Albany',
        'Albuquerque',
        'Alexandria',
        'Alhambra',
        'Aliquippa',
        'Aliso Viejo',
        'Allentown',
        'Alpharetta',
        'Altoona',
        'Ames',
        'Amesbury',
        'Anaconda',
        'Anaheim',
        'Anchorage',
        'Anderson',
        'Ann Arbor',
        'Annapolis',
        'Ansonia',
        'Apple Valley',
        'Appleton',
        'Arcadia',
        'Ardmore',
        'Areceibo',
        'Arlington',
        'Artesia',
        'Arvada',
        'Asbury Park',
        'Asheville',
        'Ashland',
        'Aspen',
        'Astoria',
        'Athens',
        'Atlanta',
        'Atlantic City',
        'Attleboro',
        'Atwater',
        'Auburn',
        'Auburn Hills',
        'Augusta',
        'Aurora',
        'Austin',
        'Avalon',
        'Azusa',
        'Bakersfield',
        'Baldwin Park',
        'Baltimore',
        'Bandera',
        'Bandon',
        'Bangor',
        'Barre',
        'Barrow',
        'Bartlesville',
        'Basin',
        'Batavia',
        'Baton Rouge',
        'Battle Creek',
        'Bay City',
        'Bay St. Louis',
        'Bayamon',
        'Baytown',
        'Beacon',
        'Beaumont',
        'Beaver Falls',
        'Beckley',
        'Bell',
        'Bell Gardens',
        'Belleville',
        'Bellflower',
        'Bellingham',
        'Beloit',
        'Belpre',
        'Bend',
        'Benton Harbor',
        'Bentonville',
        'Berkeley',
        'Berlin',
        'Bessemer',
        'Bethany',
        'Bethlehem',
        'Beverly',
        'Beverly Hills',
        'Biddeford',
        'Billings',
        'Biloxi',
        'Binghamton',
        'Birmingham',
        'Bismarck',
        'Blacksburg',
        'Bloomington',
        'Blythe',
        'Boise',
        'Bossier City',
        'Boston',
        'Boulder',
        'Boulder City',
        'Boulder Junction',
        'Bowie',
        'Bowling Green',
        'Bozeman',
        'Bradbury',
        'Bradford',
        'Branson',
        'Brea',
        'Bremerton',
        'Bridgeport',
        'Brigham City',
        'Bristol',
        'Brockton',
        'Broken Arrow',
        'Brookfield',
        'Brookings',
        'Brooklyn Park',
        'Brown Deer',
        'Brownsville',
        'Brunswick',
        'Buena Park',
        'Buffalo',
        'Burbank',
        'Burlingame',
        'Burlington',
        'Butler',
        'Butte',
        'Caguas',
        'Cairo',
        'Calabasas',
        'Calumet City',
        'Cambridge',
        'Camden',
        'Canandaigua',
        'Canton',
        'Cape Coral',
        'Cape Girardeau',
        'Cape May',
        'Carbondale',
        'Carolina',
        'Carrollton',
        'Carson',
        'Carson City',
        'Cary',
        'Casper',
        'Catskill',
        'Cedar City',
        'Cedar Falls',
        'Cedar Rapids',
        'Cedarburg',
        'Centennial',
        'Cerritos',
        'Champaign',
        'Chandler',
        'Charleston',
        'Charleston',
        'Charlotte',
        'Charlotte Amalie',
        'Charlottesville',
        'Chattanooga',
        'Chelsea',
        'Chesapeake',
        'Chester',
        'Cheyenne',
        'Chicago',
        'Chicago Heights',
        'Chickasha',
        'Chico',
        'Chicopee',
        'Chino',
        'Chino Hills',
        'Christiansted',
        'Chula Vista',
        'Cicero',
        'Cincinnati',
        'Citrus Heights',
        'City of Industry',
        'Clairton',
        'Claremont',
        'Claremore',
        'Clarksburg',
        'Clarksville',
        'Clearwater',
        'Clemson',
        'Cleveland',
        'Clovis',
        'Coatesville',
        'Cody',
        'Cohoes',
        'College Park',
        'College Station',
        'Colorado Springs',
        'Columbia',
        'Columbia',
        'Columbus',
        'Columbus',
        'Commerce',
        'Compton',
        'Concord',
        'Concord',
        'Connellsville',
        'Coos Bay',
        'Coral Springs',
        'Corinth',
        'Corona',
        'Corpus Christi',
        'Corry',
        'Cortland',
        'Corvallis',
        'Costa Mesa',
        'Council Bluffs',
        'Covina',
        'Covington',
        'Cranston',
        'Crown Point',
        'Cruz Bay',
        'Cudahy',
        'Culver City',
        'Cumberland',
        'Cypress',
        'Dallas',
        'Dalton',
        'Daly City',
        'Dana Point',
        'Danbury',
        'Danville',
        'Darlington',
        'Davenport',
        'Davis',
        'Dayton',
        'Deadwood',
        'Dearborn',
        'Decatur',
        'DeKalb',
        'Del Rio',
        'Delta Junction',
        'Denver',
        'Derby',
        'Des Moines',
        'Detroit',
        'Diamond Bar',
        'Dickinson',
        'Dixon',
        'Dodge City',
        'Dothan',
        'Douglas',
        'Dover',
        'Dover',
        'Downey',
        'Duarte',
        'DuBois',
        'Dubuque',
        'Duluth',
        'Duncan',
        'Dunkirk',
        'Duquesne',
        'Durango',
        'Durant',
        'Durham',
        'East Hartford',
        'East Lansing',
        'East Rutherford',
        'East St. Louis',
        'Easthampton',
        'Easton',
        'Eatontown',
        'Eau Claire',
        'Eden Prairie',
        'Edina',
        'Edmond',
        'Effingham',
        'Egg Harbor',
        'El Cerrito',
        'El Monte',
        'El Paso',
        'El Segundo',
        'Elizabeth City',
        'Elkhart',
        'Elko',
        'Elmira',
        'Elsmere',
        'Enfield',
        'Enid',
        'Ephraim',
        'Erie',
        'Escondido',
        'Eufaula',
        'Eugene',
        'Eureka',
        'Evanston',
        'Evansville',
        'Everett',
        'Fairbanks',
        'Fairfax',
        'Fairfield',
        'Fairmont',
        'Fajardo',
        'Fall River',
        'Fallon',
        'Falls Church',
        'Fargo',
        'Farmer City',
        'Farmington',
        'Farrell',
        'Fayetteville',
        'Fernley',
        'Fitchburg',
        'Flagstaff',
        'Flint',
        'Florence',
        'Fond du Lac',
        'Fontana',
        'Forest Lake',
        'Forrest City',
        'Fort Collins',
        'Fort Dodge',
        'Fort Lauderdale',
        'Fort Smith',
        'Fort Wayne',
        'Fort Worth',
        'Fountain Valley',
        'Frankfort',
        'Franklin',
        'Frederick',
        'Fredericksburg',
        'Frederiksted',
        'Fremont',
        'Fresno',
        'Frisco',
        'Fullerton',
        'Fulton',
        'Gadsden',
        'Gainesville',
        'Gaithersburg',
        'Galesburg',
        'Gallup',
        'Galveston',
        'Garden Grove',
        'Gardena',
        'Gardner',
        'Garland',
        'Gary',
        'Gastonia',
        'Gatlinburg',
        'Geneva',
        'Georgetown',
        'Gettysburg',
        'Gilbert',
        'Gilette',
        'Glen Cove',
        'Glendale',
        'Glendora',
        'Glens Falls',
        'Gloucester',
        'Gloversville',
        'Gold Beach',
        'Goose Creek',
        'Grafton',
        'Grambling',
        'Grand Forks',
        'Grand Island',
        'Grand Junction',
        'Grand Rapids',
        'Grass Valley',
        'Great Falls',
        'Green Bay',
        'Green River',
        'Greenfield',
        'Greensboro',
        'Greensburg',
        'Greenville',
        'Gu',
        'Guayama',
        'Guayanilla',
        'Gulfport',
        'Guthrie',
        'Hackensack',
        'Hagerstown',
        'Half Moon Bay',
        'Hamilton',
        'Hammond',
        'Hampton',
        'Hanahan',
        'Hannibal',
        'Harrisburg',
        'Hartford',
        'Hartford',
        'Hartland',
        'Hastings',
        'Hattiesburg',
        'Haverhill',
        'Hawaiian Gardens',
        'Hawthorne',
        'Hayward',
        'Hazleton',
        'Healdsburg',
        'Helena',
        'Henderson',
        'Hermitage',
        'Hermosa Beach',
        'Hialeah',
        'Hickory',
        'Hidden Hills',
        'High Point',
        'Highland Park',
        'Hilo',
        'Hoboken',
        'Hollister',
        'Hollywood',
        'Holyoke',
        'Homer',
        'Honolulu',
        'Hoover',
        'Hope',
        'Hopkinsville',
        'Hornell',
        'Hot Springs',
        'Houma',
        'Houston',
        'Hudson',
        'Huntington',
        'Huntington Beach',
        'Huntington Park',
        'Huntsville',
        'Hutchinson',
        'Idabel',
        'Idaho Falls',
        'Idaho Springs',
        'Independence',
        'Indianapolis',
        'Indio',
        'Inglewood',
        'International Falls',
        'Iowa City',
        'Irvine',
        'Irving',
        'Irwindale',
        'Isle of Palms',
        'Ithaca',
        'Jackson',
        'Jackson',
        'Jacksonville',
        'Jamestown',
        'Janesville',
        'Jeannette',
        'Jefferson City',
        'Jeffersontown',
        'Jeffersonville',
        'Jenks',
        'Jersey City',
        'Johnson City',
        'Johnstown',
        'Joliet',
        'Jonesboro',
        'Joplin',
        'Jordan Valley',
        'Juneau',
        'Kahului',
        'Kalamazoo',
        'Kalispell',
        'Kankakee',
        'Kansas City',
        'Kearney',
        'Kearns',
        'Keene',
        'Kemmerer',
        'Kenner',
        'Kennesaw',
        'Kennewick',
        'Kenosha',
        'Kent',
        'Ketchikan',
        'Kettering',
        'Kingsport',
        'Kingston',
        'Klamath Falls',
        'Knoxville',
        'Kokomo',
        'Kona',
        'La Ca',
        'La Crosse',
        'La Habra',
        'La Habra Heights',
        'La Jolla',
        'La Mirada',
        'La Palma',
        'La Puente',
        'La Verne',
        'Laconia',
        'Lafayette',
        'LaGrange',
        'Laguna Beach',
        'Laguna Hills',
        'Laguna Niguel',
        'Laguna Woods',
        'Lahaina',
        'Lake Charles',
        'Lake Forest',
        'Lakeland',
        'Lakewood',
        'Lancaster',
        'Lander',
        'Lansing',
        'Laramie',
        'Laredo',
        'Las Cruces',
        'Las Vegas',
        'Latrobe',
        'Laughlin',
        'Laurel',
        'Lawndale',
        'Lawrence',
        'Lawrenceville',
        'Lawton',
        'Layton',
        'Lebanon',
        'Leominster',
        'Lewiston',
        'Lexington',
        'Liberal',
        'Lima',
        'Lincoln',
        'Little Falls',
        'Little Rock',
        'Littleton',
        'Livonia',
        'Lock Haven',
        'Lockport',
        'Lodi',
        'Logan',
        'Lomita',
        'Long Beach',
        'Longview',
        'Los Alamitos',
        'Los Angeles',
        'Loudon',
        'Louisville',
        'Lowell',
        'Lower Burrell',
        'Lubbock',
        'Lufkin',
        'Lynchburg',
        'Lynn',
        'Lynwood',
        'Macomb',
        'Macon',
        'Madison',
        'Malden',
        'Malibu',
        'Manassas',
        'Manassas Park',
        'Manchester',
        'Mandan',
        'Manhattan',
        'Manhattan Beach',
        'Manitowoc',
        'Mankato',
        'Marietta',
        'Marlborough',
        'Marquette',
        'Marshall',
        'Marshfield',
        'Martinsburg',
        'Mason City',
        'Mayag',
        'Maywood',
        'McAlester',
        'McAllen',
        'McKeesport',
        'Meadville',
        'Mechanicville',
        'Medford',
        'Melrose',
        'Memphis',
        'Menomonee Falls',
        'Mentor',
        'Mequon',
        'Merced',
        'Meriden',
        'Meridian',
        'Merizo',
        'Mesa',
        'Mesquite',
        'Methuen',
        'Miami',
        'Miami Beach',
        'Miami Gardens',
        'Michigan City',
        'Middlebury',
        'Middletown',
        'Midland',
        'Midwest City',
        'Milford',
        'Milwaukee',
        'Minneapolis',
        'Minnetonka',
        'Minot',
        'Mission Viejo',
        'Missoula',
        'Mobile',
        'Modesto',
        'Moline',
        'Monongahela',
        'Monroe',
        'Monrovia',
        'Montebello',
        'Monterey',
        'Monterey Park',
        'Montgomery',
        'Montpelier',
        'Moore',
        'Moorhead',
        'Moraga',
        'Moreno Valley',
        'Morgan City',
        'Morgantown',
        'Morrison',
        'Moscow',
        'Moultrie',
        'Mount Pleasant',
        'Mount Vernon',
        'Muncie',
        'Murfreesboro',
        'Murray',
        'Murrieta',
        'Muskegon',
        'Muskogee',
        'Myrtle Beach',
        'Nacogdoches',
        'Nampa',
        'Nanticoke',
        'Naperville',
        'Narragansett',
        'Nashua',
        'Nashville',
        'Natchez',
        'Natchitoches',
        'Needham',
        'Nenana',
        'Nevada City',
        'New Albany',
        'New Bedford',
        'New Britain',
        'New Brunswick',
        'New Castle',
        'New Haven',
        'New Iberia',
        'New Kensington',
        'New London',
        'New Madrid',
        'New Orleans',
        'New Rochelle',
        'New York',
        'Newark',
        'Newburgh',
        'Newburyport',
        'Newcastle',
        'Newport',
        'Newport Beach',
        'Newport News',
        'Newton',
        'Niagara Falls',
        'Nichols Hills',
        'Nogales',
        'Nome',
        'Norfolk',
        'Normal',
        'Norman',
        'North Adams',
        'North Charleston',
        'North Chicago',
        'North Las Vegas',
        'North Little Rock',
        'North Platte',
        'North Pole',
        'North Tonawanda',
        'Northampton',
        'Norton',
        'Norwalk',
        'Norwich',
        'Oak Ridge',
        'Oakland',
        'Ocean City',
        'Odessa',
        'Ogden',
        'Ogdensburg',
        'Oil City',
        'Oklahoma City',
        'Olean',
        'Olympia',
        'Omaha',
        'Oneida',
        'Oneonta',
        'Ontario',
        'Opelousas',
        'Orange',
        'Orangeburg',
        'Orem',
        'Orlando',
        'Oro Valley',
        'Oshkosh',
        'Oswego',
        'Overland Park',
        'Owensboro',
        'Oxford',
        'Oxnard',
        'Paducah',
        'Palm Springs',
        'Palmdale',
        'Palo Alto',
        'Palos Verdes Estates',
        'Paramount',
        'Parker',
        'Parkersburg',
        'Parma',
        'Pasadena',
        'Pascagoula',
        'Pasco',
        'Pass Christian',
        'Passaic',
        'Paterson',
        'Pawtucket',
        'Peabody',
        'Peekskill',
        'Pembroke Pines',
        'Pendleton',
        'Peoria',
        'Perth Amboy',
        'Peru',
        'Phenix City',
        'Philadelphia',
        'Phoenix',
        'Pico Rivera',
        'Pierre',
        'Pine Bluff',
        'Pittsburgh',
        'Pittsfield',
        'Pittston',
        'Placentia',
        'Plainfield',
        'Plano',
        'Plantation',
        'Plattsburgh',
        'Plymouth',
        'Pocatello',
        'Pomona',
        'Ponce',
        'Port Arthur',
        'Port Huron',
        'Port Jervis',
        'Port Orford',
        'Port St. Lucie',
        'Port Washington',
        'Portland',
        'Portsmouth',
        'Pottsville',
        'Poughkeepsie',
        'Powell',
        'Prescott',
        'Princeton',
        'Providence',
        'Provo',
        'Pueblo',
        'Pulaski',
        'Pullman',
        'Quincy',
        'Racine',
        'Radford',
        'Raleigh',
        'Rancho Cordova',
        'Rancho Cucamonga',
        'Rancho Palos Verdes',
        'Rancho Santa Margarita',
        'Rapid City',
        'Rawlins',
        'Reading',
        'Redding',
        'Redlands',
        'Redondo Beach',
        'Reedsport',
        'Rehoboth Beach',
        'Reno',
        'Rensselaer',
        'Revere',
        'Rhinelander',
        'Rialto',
        'Richland',
        'Richmond',
        'Richmond',
        'Riverside',
        'Riverton',
        'Roanoke',
        'Rochester',
        'Rock Island',
        'Rock Springs',
        'Rockford',
        'Rockville',
        'Rocky Mount',
        'Rohnert Park',
        'Rolla',
        'Rolling Hills',
        'Rolling Hills Estates',
        'Rome',
        'Rosemead',
        'Roseville',
        'Roswell',
        'Ruston',
        'Rutland',
        'Rye',
        'Sacramento',
        'Saginaw',
        'Saint Albans',
        'Saint Cloud',
        'Saint Joseph',
        'Saint Louis',
        'Saint Paul',
        'Saipan',
        'Salem',
        'Salem',
        'Salinas',
        'Salisbury',
        'Salt Lake City',
        'San Angelo',
        'San Antonio',
        'San Bernardino',
        'San Clemente',
        'San Diego',
        'San Dimas',
        'San Fernando',
        'San Francisco',
        'San Gabriel',
        'San Jose',
        'San Juan',
        'San Juan Capistrano',
        'San Luis Obispo',
        'San Marino',
        'San Mateo',
        'San Rafael',
        'Sandpoint',
        'Sandy',
        'Sandy Springs',
        'Sanford',
        'Santa Ana',
        'Santa Barbara',
        'Santa Clara',
        'Santa Clarita',
        'Santa Cruz',
        'Santa Fe',
        'Santa Fe Springs',
        'Santa Monica',
        'Santa Rosa',
        'Saratoga Springs',
        'Saukville',
        'Sault Ste. Marie',
        'Savannah',
        'Scarborough',
        'Schaumburg',
        'Schenectady',
        'Scottsbluff',
        'Scottsdale',
        'Scranton',
        'Seaford',
        'Seal Beach',
        'Seattle',
        'Sedalia',
        'Selma',
        'Seward',
        'Shamokin',
        'Sharon',
        'Shawnee',
        'Sheboygan',
        'Shelton',
        'Sheridan',
        'Sherrill',
        'Shreveport',
        'Sierra Madre',
        'Sierra Vista',
        'Signal Hill',
        'Simi Valley',
        'Sioux City',
        'Sioux Falls',
        'Sister Bay',
        'Sitka',
        'Slidell',
        'Somersworth',
        'Somerville',
        'Sonoma',
        'South Bend',
        'South Burlington',
        'South El Monte',
        'South Gate',
        'South Pasadena',
        'South Portland',
        'Spartanburg',
        'Spokane',
        'Spokane Valley',
        'Springdale',
        'Springfield',
        'Springfield',
        'St. George',
        'St. Marys',
        'St. Petersburg',
        'Stafford',
        'Stamford',
        'Stanton',
        'Starkville',
        'Statesboro',
        'Staunton',
        'Steubenville',
        'Stevens Point',
        'Stillwater',
        'Stockton',
        'Sturgis',
        'Suffolk',
        'Sugar Land',
        'Sun Valley',
        'Sunbury',
        'Sunnyvale',
        'Superior',
        'Sutter Creek',
        'Syracuse',
        'Tacoma',
        'Tallahassee',
        'Tampa',
        'Tamuning',
        'Taunton',
        'Taylorsville',
        'Temecula',
        'Tempe',
        'Temple City',
        'Terre Haute',
        'Texarkana',
        'Texas City',
        'The Dalles',
        'Thibodaux',
        'Thiensville',
        'Thomasville',
        'Thousand Oaks',
        'Titusville',
        'Tok',
        'Toledo',
        'Tonawanda',
        'Topeka',
        'Torrance',
        'Torrington',
        'Trenton',
        'Troy',
        'Truth or Consequences',
        'Tucson',
        'Tulsa',
        'Tupelo',
        'Turlock',
        'Tuscaloosa',
        'Tustin',
        'Twin Falls',
        'Two Rivers',
        'Tyler',
        'Union City',
        'Uniontown',
        'Urbana',
        'Utica',
        'Vacaville',
        'Vail',
        'Valdez',
        'Valdosta',
        'Valencia',
        'Vallejo',
        'Valparaiso',
        'Vancouver',
        'Ventura',
        'Vergennes',
        'Vermillion',
        'Vernon',
        'Vicksburg',
        'Victoria',
        'Villa Park',
        'Vincennes',
        'Vineland',
        'Virginia Beach',
        'Visalia',
        'Waco',
        'Wahoo',
        'Walla Walla',
        'Walnut',
        'Waltham',
        'Warner Robins',
        'Warren',
        'Warwick',
        'Washington',
        'Waterbury',
        'Waterloo',
        'Watertown',
        'Watervliet',
        'Waukegan',
        'Wausau',
        'Waycross',
        'Webster Groves',
        'Weirton',
        'West Allis',
        'West Bend',
        'West Covina',
        'West Hartford',
        'West Haven',
        'West Hollywood',
        'West Jordan',
        'West Lafayette',
        'West Memphis',
        'West Palm Beach',
        'West Sacramento',
        'West Springfield',
        'West Valley City',
        'West Warwick',
        'Westfield',
        'Westlake Village',
        'Westminster',
        'Weymouth',
        'Wheaton',
        'Wheeling',
        'White Plains',
        'Whittier',
        'Wichita',
        'Wichita Falls',
        'Wilkes-Barre',
        'Williamsburg',
        'Williamsport',
        'Williston',
        'Wilmington',
        'Wilson',
        'Winnemucca',
        'Winooski',
        'Winston-Salem',
        'Wisconsin Dells',
        'Wisconsin Rapids',
        'Woburn',
        'Woodruff',
        'Woodward',
        'Woonsocket',
        'Worcester',
        'Worland',
        'Wynne',
        'Yakima',
        'Yazoo City',
        'Yigo',
        'Yonkers',
        'Yorba Linda',
        'York',
        'Youngstown',
        'Ypsilanti',
        'Yukon',
        'Yuma',
        'Zanesville',
    );
}