<?php

/**
 * Generate
 *
 * @category   Library
 * @package    Generate
 * @subpackage Generator
 */
/**
 * @see Generator_Abstract
 */
require_once 'generator_abstract_predefined.php';

/**
 * Class for generating company names.
 *
 * @category   Library
 * @package    Generator
 * @subpackage Company Name
 */
class Generator_CompanyName extends Generator_Abstract_Predefined
{
    /**
     * Predefined company names
     *
     * @var array
     */
    protected $_predefinedValues = array(
        'A&M Records',
        'A&P',
        'A&W Root Beer',
        'ABN AMRO',
        'Accenture',
        'Acer',
        'Adecco',
        'Adidas',
        'Adobe Systems',
        'Ahold',
        'Ahlstrom',
        'Akai',
        'Akamai',
        'AKZO',
        'AKG Acoustics',
        'Alcatel-Lucent',
        'Alcoa',
        'Aldi',
        'Alfa Romeo',
        'Alstom',
        'AltaVista',
        'ALZA',
        'Amazon.com',
        'AmBev',
        'AMC Theatres',
        'AMD',
        'AMKOR',
        'Amiga Corporation',
        'Amoco',
        'Amstrad',
        'Anheuser-Busch InBev',
        'Antrix Corporation',
        'AOL',
        'Apache',
        'Apple',
        'Apricot Computers',
        'Arcelor',
        'AREVA',
        'Aricent',
        'ARM Limited',
        'Arm & Hammer',
        'ARP',
        'Artis',
        'Asda',
        'ASICS',
        'Ask.com',
        'Asus',
        'Aston Martin',
        'AT&T',
        'Atari',
        'ATI',
        'ATS',
        'Audi',
        'B&Q',
        'Bahco',
        'Bang & Olufsen',
        'Bally',
        'Banesto',
        'BAPE',
        'BASF',
        'Bauknecht',
        'Bayer',
        'BBC',
        'BBVA',
        'BCC Research',
        'BEA Systems',
        'BenQ',
        'BHP',
        'BIC Corporation',
        'Black & Decker',
        'Blaupunkt',
        'BMW',
        'Boeing',
        'Bosch',
        'Bose Corporation',
        'BSNL',
        'BP',
        'BRAC',
        'Bridgestone',
        'Brine, Corp.',
        'BSA',
        'BT',
        'Bull',
        'Burroughs Corporation',
        'Bultaco',
        'BHEL',
        'CA',
        'C&A',
        'Cadillac',
        'CAE',
        'Campagnolo',
        'Canon',
        'Caprabo',
        'Carrefour',
        'Caterpillar',
        'Cathay Pacific Airways Limited',
        'Casio',
        'CBS',
        'CDAC',
        'Celera',
        'Cenex',
        'CGI Group',
        'Chevrolet',
        'Chello',
        'Chrysler',
        'Ciba Geigy',
        'Cigna',
        'Cincom',
        'Cisco',
        'Citroën',
        'Coca-Cola',
        'Coleco',
        'Colgate-Palmolive',
        'COLT',
        'Comcast',
        'Compaq',
        'COMSAT',
        'ConocoPhillips',
        'Copersucar',
        'Corel',
        'Cosworth',
        'CPFL',
        'Crabtree & Evelyn',
        'Cray',
        'CRC Press',
        'Cromemco',
        'Cutco',
        'CVS',
        'Daewoo',
        'DAF Trucks',
        'Daihatsu',
        'Danone',
        'Datsun',
        'Debian',
        'DEC',
        'DEKA',
        'Delhaize',
        'Dell',
        'Denning & Fourcade, Inc.',
        'DHL',
        'Digg, Inc.',
        'Digi-Key',
        'The Walt Disney Company',
        'Dixons',
        'DKNY',
        'Dow',
        'Duane Reade',
        'Dynegy',
        'EA Games',
        'eBay',
        'EDS',
        'Eidos',
        'Eletropaulo',
        'Embraer',
        'EMBRAPA',
        'EMBRATEL',
        'EMC Corporation',
        'EMI',
        'Emporis',
        'Equifax',
        'Ernst & Young',
        'ESPN',
        'ESRI',
        'Epson',
        'Esso',
        'Exxon',
        'FAS',
        'Facebook',
        'Fair Isaac Corporation',
        'Fazer',
        'FCUK',
        'FedEx',
        'Fegime',
        'Ferodo',
        'Ferrari',
        'Fiat',
        'Finnair',
        'Firestone',
        'Five Guys',
        'Fluke',
        'Ford Motor Company',
        'Forrester Research',
        'FranklinCovey',
        'Fuji',
        'Garmin',
        'Gartner',
        'GCap Media',
        'Genentech',
        'GEICO',
        'Gerdau',
        'Glaxo',
        'Glock Ges.m.b.H.',
        'Goodyear',
        'Google',
        'Grey Global Group',
        'Grundig',
        'Gulfstream Aerospace',
        'Häagen-Dazs',
        'Haier',
        'H&M',
        'Haribo',
        'Harman Kardon',
        'Harpo Productions',
        'Hasbro',
        'HBOS',
        'HCL',
        'Hess Corporation',
        'HP',
        'Hispano-Suiza',
        'Hitachi',
        'HMV',
        'Hoechst',
        'Honda',
        'Honeywell',
        'Hospira',
        'Hotmail',
        'H&R Block',
        'HSBC',
        'HTC Corporation',
        'Hyundai',
        'IBM',
        'ICL',
        'IG Farben',
        'Iiyama',
        'IKEA',
        'IMI',
        'InBev',
        'Inditex',
        'Infineon Technologies',
        'Ingenico',
        'Intel',
        'Ittiam Systems',
        'Infosys',
        'J2TV',
        'JAL',
        'Jat Airways',
        'Jawa Motors',
        'JBL',
        'Johnson & Johnson',
        'JVC',
        'Kalev',
        'Kawasaki',
        'KFC',
        'Kenwood Limited',
        'Kenworth',
        'Kia Motors',
        'Kmart',
        'Kodak',
        'Komatsu',
        'Konica',
        'Korg',
        'KPMG',
        'Kroger',
        'KUKA',
        'Kyocera',
        'Lada',
        'Lancôme',
        'LCL',
        'Lego',
        'Lenovo Group',
        'Level 3 Communications',
        'LG',
        'Lexmark',
        'Lionbridge',
        'Lionhead Studios',
        'Lockheed Martin',
        'LoJack',
        'Longines',
        'Lonsdale',
        'LOT',
        'Lotus Software',
        'Lucent Technologies',
        'Lukoil',
        'Lycos',
        'Maggi',
        'MAN',
        'Mandriva',
        'Manhattan Associates',
        'Manugistics',
        'Manulife Financial',
        'Mars',
        'Masco Corporation',
        'Mast-Jägermeister AG',
        'Mattel',
        'Maybach-Motorenbau GmbH',
        'Mazda Motor Corporation',
        'MBNA',
        'MCI Communications',
        'Mercedes',
        'Merillat Industries',
        'Metro-Goldwyn-Mayer',
        'MFI',
        'MG Cars',
        'Microlins',
        'Micron Technology',
        'Microsoft',
        'Midway Games',
        'Mincom Limited',
        'Minolta',
        'MIPRO',
        'MIPS',
        'MITIE',
        'Mitel',
        'MITRE',
        'Mitsubishi',
        'Moneris Solutions',
        'Morningstar, Inc.',
        'Motorola',
        'Mozilla Foundation',
        'MVC',
        'Mustek',
        'MRF',
        'Nabisco',
        'NAD Electronics',
        'Napster',
        'NCR Corporation',
        'NEC',
        'Nero',
        'Nestlé',
        'Netscape',
        'Nike',
        'Nikon',
        'Nintendo',
        'Nissan',
        'Nokia',
        'Nortel Networks',
        'Novartis',
        'Novell',
        'OCZ',
        'Oracle',
        'Ornge',
        'Osram',
        'Paccar',
        'PCCW',
        'Pamida',
        'Pemex',
        'Pennzoil',
        'Pepsi',
        'Petrobras',
        'Philco',
        'Philips',
        'Pixar',
        'PMC-Sierra',
        'Porsche',
        'Prada',
        'Procter & Gamble',
        'ProfSat',
        'PRS Guitars',
        'Psion',
        'Q8',
        'Qantas',
        'Qimonda',
        'Quad',
        'Quark',
        'Qualcomm',
        'QVC',
        'Rabobank',
        'RAND',
        'Raytheon',
        'RCA',
        'Reckitt & Colman',
        'Reckitt Benckiser',
        'Red Hat',
        'Reebok',
        'REO Motor Car Company',
        'Repsol',
        'Research In Motion',
        'Rickenbacker',
        'Robeez',
        'Rolls-Royce',
        'RSA Security',
        'Saab',
        'Sabre',
        'Saku Brewery',
        'Samsonite',
        'Samsung',
        'Sanyo',
        'SAP',
        'SAS',
        'SAS Institute',
        'Sasol',
        'SCB',
        'SCO',
        'Saudi Aramco',
        'Schick',
        'SEAT',
        'Sealed Air',
        'Sega',
        'Seiko',
        'Sennheiser',
        'setcom',
        'SGI',
        'Sharp',
        'Shell',
        'Siemens',
        'Six Apart',
        'Skanska',
        'SKF',
        'Skoda Auto',
        'Skype',
        'Smart',
        'Smilebit',
        'Smeg',
        'SNK',
        'Sony',
        'Sorcim',
        'SPAR',
        'Sperry',
        'Spiratone',
        'Sprint',
        'SRAM Corporation',
        'SRI International',
        'Stanley Works',
        'Starbucks',
        'Stellent',
        'STX',
        'Subaru',
        'Sun Microsystems',
        'SuSE',
        'Suzuki',
        'Taco Bell',
        'Talgo',
        'TAM Airlines',
        'TAP Portugal',
        'Tata Group',
        'Taxan',
        'TCBY',
        'TCL',
        'TCS',
        'TDK Corporation',
        'Tesco',
        'Teva Naot',
        'Texaco',
        'THX',
        'TIBCO Software',
        'Tim Hortons',
        'TNT N.V.',
        'Toshiba',
        'Toyota',
        'Triang',
        'Tucows',
        'TVR',
        'Twinings',
        'Twitter',
        'Ubuntu Foundation',
        'Umbro',
        'Unilever',
        'UNIMED',
        'Unisys',
        'Unocal Corporation',
        'UPS',
        'UUNET',
        'Vaisala',
        'Valtra',
        'Varig',
        'Verizon',
        'Virgin',
        'VMware',
        'Vodafone',
        'Volkswagen',
        'Volvo',
        'Wachovia',
        'Waitrose',
        'Walgreens',
        'Wal-Mart',
        'Wang Laboratories',
        'Wells Fargo',
        'Weta Digital',
        'W H Smith',
        'Williams-Sonoma',
        'Wipro',
        'World Wrestling Entertainment',
        'Worlds of Wonder',
        'WPP',
        'Xerox',
        'Yahoo!',
        'YKK',
        'Yakult',
        'Yoplait',
        'Zend Technologies',
        'Zero Halliburton',
        'Zuse',
    );
}